name: "Build and Test"
on:
  pull_request:

jobs:
  build-and-test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: 📥 Install Dependencies
        run: yarn --frozen-lockfile

      - name: "Build"
        run: yarn build

      - name: run coverage
        run: yarn test:coverage

        # Remove node_modules to see if this action runs entirely compiled
      - name: "Remove Node Modules"
        run: rm -rf node_modules

      - name: "Curren Repo"
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-all-projects: "true"
          name: "Mock Reports"

      - name: "Test Normal Repo"
        uses: ./
        with:
          repo-cwd: "./tests/mockReports"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-all-projects: "true"
          name: "Mock Reports"

      - name: "Test Mono Repo"
        uses: ./
        with:
          repo-cwd: "./tests/mockMonoReports"
          include-all-projects: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: "Mock Mono Reports"
  