name: "Build and Test"
on:
  pull_request:

jobs:
  build-and-test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: 📥 Install Dependencies
        run: yarn --frozen-lockfile

      - name: "Build"
        run: yarn build

        # Remove node_modules to see if this action runs entirely compiled
      - name: "Remove Node Modules"
        run: rm -rf node_modules

      - name: "Test Working Directory Option"
        uses: ./
        with:
          working-directory: "./tests/mockReports"
          name: "Mock Reports"
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          # Allows to download / query / comment packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
